version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vanguard
    environment:
      MYSQL_ROOT_PASSWORD: vg_admin_password
      MYSQL_DATABASE: vanguard
      MYSQL_USER: vg_user
      MYSQL_PASSWORD: vg_user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
