spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:vanguard}
    username: ${DATABASE_USERNAME:vg_user}
    password: ${DATABASE_PASSWORD:vg_user_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080
