spring:
  application:
    name: vanguard

  security:
    user:
        name: ${SECURITY_USER_NAME:admin}
        password: ${SECURITY_USER_PASSWORD:password}
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8180/realms/vanguard/protocol/openid-connect/certs}

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:vanguard}
    username: ${DATABASE_USERNAME:vg_user}
    password: ${DATABASE_PASSWORD:vg_user_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
